### ISSUE TITLE
Kernel .config is missing

### ISSUE THREAD

**Issue by thasti** [myriadrf/SNOWLeo-SDR#5]
The Kernel configuration is missing, so build is not reproducible. Generally: Is this repository totally outdated compared to the v3best-Repository? Sadly, it has the various other problems (but the .config is missing there as well).

This whole project seems abandoned.

**Comment by v3tech** [comment]
SnowleoSDR kernel config is <firmware/src/linux/arch/arm/configs/v3best_snowleo_defconfig>

**Comment by v3tech** [comment]
firmware/src/linux/arch/arm/configs/v3best_snowleo_defconfig
